name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    timeout-minutes: 45  # Augmenté pour donner plus de temps

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcsclite-dev swig python3-tk

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install swig
        brew install create-dmg

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-input -r requirements.txt
        pip install pyinstaller

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --log-level DEBUG --onefile --add-data "pysatochip\pysatochip\cert\*;pysatochip/pysatochip/cert" --add-data "pictures_db\*;pictures_db" --add-data "pysatochip\pysatochip\CardConnector.py;pysatochip" satochip_utils.py --name satochip_utils.exe
      timeout-minutes: 20

    - name: Build AppImage (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --log-level DEBUG --onefile --add-data "pysatochip/pysatochip/cert/*:pysatochip/pysatochip/cert" --add-data "pictures_db/*:pictures_db" --add-data "pysatochip/pysatochip/CardConnector.py:pysatochip" satochip_utils.py --name satochip_utils
        # Installer les outils nécessaires pour créer un AppImage
        sudo apt-get install -y wget
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        # Créer la structure de répertoires pour AppImage
        mkdir -p AppDir/usr/bin
        cp dist/satochip_utils AppDir/usr/bin/
        # Créer le fichier .desktop
        echo "[Desktop Entry]
        Name=Satochip Utils
        Exec=satochip_utils
        Icon=satochip_utils
        Type=Application
        Categories=Utility;" > AppDir/satochip_utils.desktop
        # Créer l'AppImage
        ./appimagetool-x86_64.AppImage AppDir
      timeout-minutes: 20

    - name: Build DMG (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --log-level DEBUG --onefile --add-data "pysatochip/pysatochip/cert/*:pysatochip/pysatochip/cert" --add-data "pictures_db/*:pictures_db" --add-data "pysatochip/pysatochip/CardConnector.py:pysatochip" satochip_utils.py --name satochip_utils
        # Créer le DMG
        create-dmg \
          --volname "Satochip Utils" \
          --window-pos 200 120 \
          --window-size 600 300 \
          --icon-size 100 \
          --icon "satochip_utils" 200 150 \
          --hide-extension "satochip_utils" \
          --app-drop-link 400 150 \
          "Satochip_Utils.dmg" \
          "dist/"
      timeout-minutes: 20

    - name: Upload artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: windows-satochip_utils
        path: dist/satochip_utils.exe

    - name: Upload artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: linux-satochip_utils
        path: Satochip_Utils-x86_64.AppImage

    - name: Upload artifact (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v3
      with:
        name: macos-satochip_utils
        path: Satochip_Utils.dmg